Car types st routes car trains
Lokideos/think_tutu pull request #3
Opened 2017-05-28 20:52 UTC by Lokideos

2017-05-29 05:58 UTC, iBublik requested changes

2017-05-29 05:58 UTC, iBublik commented on app/models/car.rb
> +    self.number_in_train = train.cars.length + 1 if train_id
Если какой-то вагон удалить, этот алгоритм вызовет дублирование номера. Лучше опираться на максимальный номер вагона

2017-05-29 05:58 UTC, iBublik commented on app/models/train.rb
> +  def sort_cars_by_position
Назови лучше `sorted_cars`, сейчас метод выглядит как команда на сортировку (изменение порядка), а по факту это запрос

2017-05-29 05:58 UTC, iBublik commented on app/models/train.rb
> +      cars.order(number_in_train: :asc)
Лучше инкапсулировать логику сортировки в класс вагонов. Создай там скоуп с параметром, который будет осуществлять сортировку в зависимости от этого параметра

2017-05-29 05:58 UTC, iBublik commented on db/migrate/20170528181727_add_sort_flag_to_train.rb
> +    add_column :trains, :sort_type, :boolean
`default: false, null: false`, чтоб не было пустых значений в логическом поле

2017-05-29 05:58 UTC, iBublik commented on db/migrate/20170518193449_add_different_car_types.rb
> +    remove_column :cars, :lateral_top_seats, :integer
А что за поля ты удаляешь? В схеме вроде и не было таких

2017-05-29 05:58 UTC, iBublik commented on db/migrate/20170518193449_add_different_car_types.rb
> +    remove_column :cars, :lateral_top_seats, :integer
Когда несколько полей меняешь в одной таблице, лучше использовать такой способ:
```ruby
change_table :cars do |t|
  t.integer :side_top_seats
  ...
end
```

2017-05-29 05:58 UTC, iBublik commented on app/views/trains/show.html.erb
> +      <% if car.type == "CattleCar" %>
Зачем каждый раз перебирать все вагоны, чтоб отобразить только нужный тип? Создай метод или скоуп в модели поездов, который будет эту логику содержать

2017-05-29 05:58 UTC, iBublik commented on app/views/routes/show.html.erb
> +    <% RailwayStationsRoute.all.where(["railway_stations_routes.route_id = ?", @route.id]).ordered.each do |association| %>
Слишком сложные запросы для вьюхи. Тут должен быть простой цикл, а логика сортировки должна лежать в моделях.

2017-05-29 07:25 UTC, Lokideos commented on db/migrate/20170528181727_add_sort_flag_to_train.rb
> +    add_column :trains, :sort_type, :boolean
А где это писать? В самой играции после `:boolean`?

2017-05-29 07:26 UTC, Lokideos commented on db/migrate/20170518193449_add_different_car_types.rb
> +    remove_column :cars, :lateral_top_seats, :integer
Вроде бы были, и я менял `:lateral_top_seats` на `:side_top_seats`.
`change_table` вписывать в метод `change`?

2017-06-01 18:02 UTC, Lokideos commented on db/migrate/20170528181727_add_sort_flag_to_train.rb
> +    add_column :trains, :sort_type, :boolean
В общем, я в итоге поменял само значение поля, но я так понял всегда надо задавать дефолтные значения для него? Или это необязательно, т.к. в руби nil интерпретируется, как false?

2017-06-01 18:45 UTC, Lokideos commented on app/views/trains/show.html.erb
> +      <% if car.type == "CattleCar" %>
Я скоуп в итоге в модель вагонов включил.

2017-06-02 06:02 UTC, iBublik commented on db/migrate/20170528181727_add_sort_flag_to_train.rb
> +    add_column :trains, :sort_type, :boolean
Для логических значений лучше задавать, чтоб в базе хранилось true/false (без null) - так будет проще работать с содержимым

2017-06-02 06:23 UTC, iBublik requested changes

2017-06-02 06:23 UTC, iBublik commented on app/models/car.rb
> +  scope :ordered_by_type, ->(car_type) { where(type: car_type) }
А почему `ordered`? Порядок тут вообще не при чем же

2017-06-02 06:23 UTC, iBublik commented on app/models/car.rb
> +    self.number_in_train = if train.cars.empty?
Проблема в том, что номер будет меняться при каждом сохранении. И можно одной строкой записать - `train.cars.maximum(:number_in_train).to_i + 1`

2017-06-02 06:23 UTC, iBublik commented on app/models/railway_stations_route.rb
> +  scope :ordered, -> { order(:station_in_route_id) }
Почему `id`, а не `number`? Тут ведь не идентификатор

2017-06-02 06:23 UTC, iBublik commented on app/models/railway_stations_route.rb
> +    if RailwayStationsRoute.all.where(['railway_stations_routes.route_id = ?', route_id]).ordered.last.nil?
Тут аналогичная проблема - при каждом сохранении записи она будет становиться последней.
Ну и запрос сложный, можно ведь воспользоваться ассоциациями (`route.railway_stations_routes.maximum(...)` - в общем, по аналогии с вагонами)

2017-06-02 06:23 UTC, iBublik commented on app/models/route.rb
> +    RailwayStationsRoute.all.where(['railway_stations_routes.route_id = ?', id]).ordered.each do |association|
Не нужно строить запросы вручную - все это нам дают ассоциации из коробки. И вообще я не вижу нужды в этом методе - мы можем перебирать коллекцию `route.railway_stations_routes.ordered` - это даст нам нужный порядок, а уже оттуда вытягивать станцию (`route.railway_stations_routes.ordered.each { |rsr| rsr.railway_station }`)

2017-06-02 06:23 UTC, iBublik commented on db/schema.rb
> +    t.string   "sort_type"
По заданию нам нужно именно логическое поле. Сортировка бывает либо по возрастанию, либо по убыванию, так что нет смысла хранить строку.

2017-06-02 06:25 UTC, Lokideos commented on db/schema.rb
> +    t.string   "sort_type"
Ох, а я хотел схитрить, вставляя туда "ASC" или "DESC" :)

2017-06-02 06:35 UTC, iBublik commented on db/schema.rb
> +    t.string   "sort_type"
Это можно разрулить на уровне скоупа в модели вагонов - если true то asc, иначе desc

2017-06-02 17:27 UTC, iBublik requested changes

2017-06-02 17:27 UTC, iBublik commented on app/models/car.rb
> +  scope :pick_type, ->(car_type) { where(type: car_type) }
Все равно не самый удачный нейминг. Создается впечатление, что метод вытаскивает из базы типы вагонов (аля `pluck(:type)`), но ведь это не так. Методы-запросы обычно не содержат в имени глаголов, какой-нибудь `with_type` тут больше подойдет. 
А вообще есть смысл создать отдельный скоуп под каждый тип вагонов, чтоб можно было использовать `train.cars.coupe`.

2017-06-02 17:27 UTC, iBublik commented on app/models/car.rb
> +    self.number_in_train = train.cars.maximum(:number_in_train).to_i + 1
Номер по-прежнему будет меняться при каждом сохранении. Проще всего проверять установлен ли номер, если установлен, то ничего не делать

2017-06-02 17:27 UTC, iBublik commented on app/models/car.rb
> +    self.number_in_train = train.cars.maximum(:number_in_train).to_i + 1
Кстати, валидация-то вообще проходит? Ты же ставишь номер перед сохранением, а это происходит уже после валидации.

2017-06-02 17:27 UTC, iBublik commented on app/models/railway_stations_route.rb
> +    self.station_in_route_number = route.railway_stations_routes.maximum(:station_in_route_number).to_i + 1
Проблемы аналогичны вагонам - номер меняется при каждом сохранении, валидация на уникальность не должна пройти, т.к. на этот момент номер еще не установлен

2017-06-02 17:27 UTC, iBublik commented on app/models/route.rb
>    def stations_in_route
Зачем этот метод теперь? К тому же название с толку сбивает, он ведь вовсе не станции возвращает

2017-06-04 08:29 UTC, Lokideos commented on app/models/car.rb
> +  scope :pick_type, ->(car_type) { where(type: car_type) }
Я просто думал, что так не соответствовать DRY будет ^_^ Сейчас все переделаю

2017-06-04 10:00 UTC, vkurennov approved these changes

2017-06-07 16:17 UTC, merged