Controllers and non standard forms for tickets trains and stations
Lokideos/think_tutu pull request #4
Opened 2017-06-08 18:14 UTC by Lokideos

2017-06-09 08:22 UTC, iBublik requested changes

2017-06-09 08:22 UTC, iBublik commented on app/controllers/cars_controller.rb
>  class CarsController < ApplicationController
Из разрешенных параметров нужно убрать `train_id`, т.к. теперь мы привязываем вагон к поезду через ассоциацию

2017-06-09 08:22 UTC, iBublik commented on app/controllers/railway_stations_controller.rb
> +  def update_departure_time
Для обновления времени прибытия/отправления лучше сделать один экшен и один метод модели - все-таки это однородная информация, имеет смысл ее вместе обновлять

2017-06-09 08:22 UTC, iBublik commented on app/controllers/searches_controller.rb
> +
Почему контроллер пустой?
И зачем на экшны edit/new? По логику у нас есть show (результат поиска) и create(создание нового поиска)

2017-06-09 08:22 UTC, iBublik commented on app/models/concerns/search.rb
> +class Search < ApplicationRecord
В чем смысл этой пустой модели? Да и не рабочая она, таблицы-то нет.
Вообще для поиска нам не нужен ActiveRecord объект, мы не будем ничего сохранять в базу. Так что лучше ограничиться простым Ruby классом

2017-06-09 08:22 UTC, iBublik commented on app/models/railway_station.rb
> +  def update_departure_time(route, departure_time)
Объедини этот метод с `update_arrival_time`

2017-06-09 08:22 UTC, iBublik commented on app/models/railway_stations_route.rb
> -  belongs_to :route
Зачем удалять этот код?

2017-06-09 08:22 UTC, iBublik commented on app/models/route.rb
> +    Route.all.each do |route|
Перебор в памяти очень неэффективен. Все то же самое можно сделать с помощью SQL запросов

2017-06-09 08:22 UTC, iBublik commented on app/views/tickets/new.html.erb
> +<%= debug(params) %>
Не забывай убирать отладку

2017-06-09 08:22 UTC, iBublik commented on app/views/tickets/new.html.erb
> +  <%= f.text_field :personal_id %>
Почему это текстовое поле?

2017-06-09 08:22 UTC, iBublik commented on db/migrate/20170607213307_add_arrival_and_departure_time_to_railway_stations_routes.rb
> +      t.integer :arrival_time
Почему это числовые поля? Время надо хранить в datetime

2017-06-09 08:22 UTC, iBublik commented on db/migrate/20170608171511_add_fio_and_personal_id_to_tickets.rb
> +      t.string :personal_id
Что за personal_id? У тебя есть user_id, используй его.

2017-06-09 08:22 UTC, iBublik commented on db/migrate/20170608171511_add_fio_and_personal_id_to_tickets.rb
> +      t.integer :departure_time
Зачем это вообще хранить? Мы знаем станцию отправления и прибытия, оттуда эту информацию можно извлечь

2017-06-09 08:22 UTC, iBublik commented on db/migrate/20170608171511_add_fio_and_personal_id_to_tickets.rb
> +      t.string :chosen_train
Нам надо хранить не строку, а связь с поездом, на который куплен билет

2017-06-09 17:45 UTC, Lokideos commented on app/controllers/searches_controller.rb
> +
А что там должно быть то? Объект Search у нас один, так что результаты поиска show сразу показываются после применения поиска из new.

2017-06-09 17:46 UTC, Lokideos commented on app/models/railway_stations_route.rb
> -  belongs_to :route
Странно, у меня все на месте.

2017-06-09 18:16 UTC, Lokideos commented on app/views/tickets/new.html.erb
> +  <%= f.text_field :personal_id %>
Так это же номер паспорта

2017-06-09 18:23 UTC, Lokideos commented on app/views/tickets/new.html.erb
> +  <%= f.text_field :personal_id %>
Так там номер паспорта, не привязанный к юзеру нужен или привязка к пользователю?

2017-06-09 18:23 UTC, Lokideos commented on app/models/route.rb
> +    Route.all.each do |route|
Я изменил там метод, который используется внутри. Сам перебор менять? Просто если не так, то через что туда можно сразу проверку по двум разным значениям одного и того же параметра впихнуть?

2017-06-10 07:59 UTC, iBublik commented on app/controllers/searches_controller.rb
> +
Пустой контроллер приводит в недоумение. А все потому что у тебя логика переместилась во вьюху. Здесь должна быть логика вызова класса Search. В идеале нам должна возвращаться сущность, содержащая список поездов, начальную и конечную станции. Чтоб во вьюхе тупо обратиться к этим значениям и вывести их

2017-06-10 08:00 UTC, iBublik commented on app/models/railway_stations_route.rb
> -  belongs_to :route
При мерже у тебя это потеряется, т.к. PR содержит иформацию об удалении этих строк

2017-06-10 08:02 UTC, iBublik commented on app/models/route.rb
> +    Route.all.each do |route|
Можно выбрать поезда, который привязны к маршрутам, содержащим первую и вторую станции (2 запроса), а уже на Ruby отсечь дубликаты

2017-06-10 08:02 UTC, iBublik commented on app/views/tickets/new.html.erb
> +  <%= f.text_field :personal_id %>
Ок, я подумал это такая связь с пользователем :)

2017-06-15 13:57 UTC, Lokideos commented on app/controllers/searches_controller.rb
> +
Я вообщем не понял, как без new обойтись и включил все в new, а create убрал

2017-06-15 13:57 UTC, Lokideos commented on app/models/railway_stations_route.rb
> -  belongs_to :route
А что делать то в этом случае?

2017-06-15 14:12 UTC, Lokideos commented on app/models/route.rb
> +    Route.all.each do |route|
Судя по всему, я примерно так и сделал :)

2017-06-15 16:30 UTC, vkurennov commented on app/models/railway_stations_route.rb
> -  belongs_to :route
Вернуть строку на место и сделать коммит.

2017-06-15 17:12 UTC, Lokideos commented on app/models/railway_stations_route.rb
> -  belongs_to :route
У меня просто в исходном коде на моей VM она есть почему-то.

2017-06-15 18:49 UTC, iBublik requested changes

2017-06-15 18:49 UTC, iBublik commented on app/controllers/searches_controller.rb
> +    Route.available_routes(params[:arrival_station_id], params[:departure_station_id]).each do |route|
Рекомендации:
1. Заполнять массив лучше через `flat_map` - это метод для итерации по коллекции и создания одномерного (плоского) массива.
2. Хорошо бы добавить `includes(:trains)` к запросу - это позволит избежать проблемы N + 1. Сейчас у тебя для каждого маршрута идет новый запрос в базу для вытаскивания поездов. А `includes` сделает то же самое за 2 запроса.

2017-06-15 18:49 UTC, iBublik commented on app/models/railway_stations_route.rb
> -  belongs_to :route
Странно, при рассинхроне локального и удаленного репозитория изменения не запушить. Попробуй сделать `git pull --rebase` в ветке задания. Еще можно посмотреть что список коммитов в локальной ветке совпадает со списком коммитов в remote ветке.

2017-06-15 18:49 UTC, iBublik commented on app/models/route.rb
> +    Route.all.each do |route|
Нет, у тебя по-прежнему проход по абсолютно всем маршрутам. Можно несложным запросом полностью заменить метод `stations_in_route?`. Просто соедини таблицу `railway_station_routes`, добавь условие на присоединенную таблицу (`where(railway_station_routes: { railway_station_id: some_id })`). Это выберет только те маршруты, у которых есть переданная станция. После этого получаешь пересечение маршрутов с начальной станцией и маршрутов с конечной станцией (для этого есть оператор `&`) - это и будет нужное множество станций

2017-06-15 18:49 UTC, iBublik commented on app/models/route.rb
> +  def stations_in_route?(arrival_station_id, departure_station_id)
Этот метод можно убрать, если сделать все через запрос

2017-06-15 18:49 UTC, iBublik commented on app/models/ticket.rb
> +  # validate :check_first_and_last_stations
Неиспользуемый код можно смело удалять, не нужно комментировать

2017-06-15 18:49 UTC, iBublik commented on db/migrate/20170615154424_remove_columns_from_tickets.rb
> +class RemoveColumnsFromTickets < ActiveRecord::Migration[5.0]
Очень много миграций, которые исправляют то что было добавлено в этой фиче. Пока миграции не в стабильной ветке, их можно смело изменять (правда перед этим стоит откатить их, или после изменения пересоздать базу с нуля).

2017-06-16 11:28 UTC, Lokideos commented on app/models/railway_stations_route.rb
> -  belongs_to :route
В общем, в ветке все есть, я на всякий случай перекачл репозиторий - там тоже все в порядке.

2017-06-16 11:28 UTC, Lokideos commented on app/models/railway_station.rb
> +  def update_departure_time(route, departure_time)
Этот метод (теперь он называется `update_travel_time`) я использую для обновления времени прибытия и отправления поезда на маршруте. Добавляется это через `show.html.erb` в `/view/routes/ `
Соответственно, я обращаюсь во вьюшке к одной из предварительно выбранных станций и выставляю там нужное мне время.

2017-06-16 12:23 UTC, Lokideos commented on db/migrate/20170615154424_remove_columns_from_tickets.rb
> +class RemoveColumnsFromTickets < ActiveRecord::Migration[5.0]
Да, я просто боюсь что-то поломать, если на много миграций назад откачусь. Может перед следующим д/з заново создам миграции для БД.

2017-06-16 12:24 UTC, Lokideos commented on app/controllers/searches_controller.rb
> +    Route.available_routes(params[:arrival_station_id], params[:departure_station_id]).each do |route|
С flat_map все здорово; с includes(:trains) не понятно, куда именно вставлять. После выборки станций?

2017-06-16 15:21 UTC, iBublik requested changes

2017-06-16 15:21 UTC, iBublik commented on app/controllers/searches_controller.rb
> +    Route.available_routes(params[:arrival_station_id], params[:departure_station_id]).each do |route|
У Ruby и Rails отличная документация, в первую очередь стоит там смотреть - http://devdocs.io/rails~4.1/activerecord/querymethods#method-i-includes. Т.к. это метод Active Record, то ты не можешь его тут применить (`available_routes` возвращает обычный массив). А вот внутри `available_routes` - можешь

2017-06-16 15:21 UTC, iBublik commented on app/controllers/searches_controller.rb
> +      @chosen_trains = route.trains.flat_map { |train| train }
Не то, ты сейчас просто взял поезда последнего маршрута. Я имел в виду `@chosen_trains = Route.available_routes(...).flat_map(&:trains)`. `flat_map` используется, когда мы хотим получить плоский массив, это как раз наш случай - каждый маршрут возвращает массив поездов, и с помощью `flat_map` вместо массива массивов мы получаем одномерный массив.

2017-06-16 15:21 UTC, iBublik commented on app/models/railway_stations_route.rb
> -  belongs_to :route
Ну на гитхабе точно не в порядке - посмотри [файл в этой ветке](https://github.com/Lokideos/think_tutu/blob/controllers_and_non_standard_forms_for_tickets_trains_and_stations/app/models/railway_stations_route.rb). Вот [ссылка](https://github.com/Lokideos/think_tutu/commit/e7ad2f9438e60b6d583857e0f15408d239c1c2fe#diff-89b7ec3336d4ad81963928f05b4ba09d) на коммит с удалением.
Не знаю почему у тебя локально все ок, но попробуй внести в этот фал какое-нибудь изменение (банально комментарий) и запушить, может все нормализуется. Иначе при мерже в мастер этот код пропадет

2017-06-16 15:21 UTC, iBublik commented on app/models/route.rb
> +  def self.available_routes(arrival_station_id, departure_station_id)
Нейминг не очень удачный - лучше назови `with_stations`. `Route.available_routes` не дает понять почему эти маршруты `available`, да и дублирование `routes` внутри класса `Route` режет слух

2017-06-16 15:21 UTC, iBublik commented on db/migrate/20170615154424_remove_columns_from_tickets.rb
> +class RemoveColumnsFromTickets < ActiveRecord::Migration[5.0]
Миграции в стабильной ветке менять нельзя. Понятно что у нас учебное приложение, с которым ты один работаешь, но лучше не заводить вредных привычек.
В общем ладно, не трогай уже эти миграции, но в дальнейшем не надо их плодить. Как откатывать миграции я писал [тут](http://connect.thinknetica.com/t/denis-toriczyn-zorro/4119/214) и [тут](https://github.com/dimasumskoy/rails-thinknetica/pull/2#discussion_r120935370).

2017-06-16 15:21 UTC, iBublik commented on app/models/route.rb
> +    Route.joins(:railway_stations_routes).where(railway_stations_routes: { railway_station_id: arrival_station_id }) &
Вот тут к запросам можно `includes` прикрутить

2017-06-16 15:21 UTC, iBublik commented on app/controllers/tickets_controller.rb
> +    @train = Train.find(@ticket.train_id)
А зачем так сложно? Можно ведь просто `@ticket.train` вызвать.

2017-06-16 16:17 UTC, Lokideos commented on app/controllers/searches_controller.rb
> +      @chosen_trains = route.trains.flat_map { |train| train }
Ой да, точно

2017-06-17 10:05 UTC, vkurennov approved these changes

2017-06-18 11:45 UTC, merged